on: [pull_request_target]

jobs:
  comment:
    if: ${{ github.event.issue.user.login != 'cxwtool' && github.ref == 'refs/heads/live' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'It looks like this PR may be opened on live branch by mistake. Unless this is a merge from main to live, PRs should normally be opened on main branch.'
            })
