name: Markdown links verifier
on: pull_request

jobs:
  validate_links:
    name: Markdown links verifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 #@v2

    - name: Validate links
      uses: Youssef1313/markdown-links-verifier@19a29ce5e217fe12392f4ac9f57cdc3dd9d41830 #@v0.1.2
